= Metanorma
:docnumber: 36010
:tc-document-number: 9999
:edition: 1
:ref-docnumber: 36010:2019(E)
:copyright-year: 2019
:language: en
:title-intro-en: Lightweight document
:title-main-en: Document metamodel
:title-intro-fr: Document léger
:title-main-fr: Métamodèle des documents
:title-part-fr:
:doctype: international-standard
:docstage: 10
:docsubstage: 92
:technical-committee-type: TC
:technical-committee-number: 154
:technical-committee: Processes, data elements and documents in commerce, industry and administration
:workgroup-type: WG
:workgroup-number: 4
:workgroup: e-Documents
:secretariat: SAC
:draft:
:toc:
:stem:
:xrefstyle: short
:local-cache-only:
:data-uri-image:
:docfile: iso-36010.adoc
:mn-document-class: iso
:mn-output-extensions: xml,html,doc,html_alt

[[foreword]]
.Foreword
ISO (the International Organization for Standardization)
is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

The procedures used to develop this document and those intended for its further maintenance are described in the ISO/IEC Directives, Part 1. In particular the different approval criteria needed for the different types of ISO documents should be noted. This document was drafted in accordance with the editorial rules of the ISO/IEC Directives, Part 2 (see www.iso.org/directives).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights. Details of any patent rights identified during the development of the document will be in the Introduction and/or on the ISO list of patent declarations received (see www.iso.org/patents).

Any trade name used in this document is information given for the convenience of users and does not constitute an endorsement.

For an explanation on the voluntary nature of standards, the meaning of ISO specific terms and expressions related to conformity assessment, as well as information about ISO's adherence to the World Trade Organization (WTO) principles in the Technical Barriers to Trade (TBT) see the following URL: www.iso.org/iso/foreword.html.

This document was prepared by Technical Committee ISO/TC {technical-committee-number}, _{technical-committee}_.

This is the first edition of this document.

[[introduction]]

:sectnums!:
== Introduction

There is a general need for interchange and interoperability of structured text amongst
information systems. While there is a plethora of richly-formatted text documents,
ranging from complex document formats like OOXML and ODF, hypertext formats like HTML,
to older formats such as RTF and presentation focused formats like PDF,
there is no standardized method of transmitting an interoperable text
structure to another system.

In addition, the popularity of lightweight text markup syntaxes like Markdown
and AsciiDoc has been hampered by practical concerns that documents generated
by such syntaxes have inherited identical issues as have the above
document formats.

This limits the exchange of structured text down to the lowest common denominator
in parsing support, which is, plain text -- that lacks any kind of
structure (human or machine understandable).

The _BasicDocument_ model is created to express the structure of generic documents
in a lightweight form.

_BasicDocument_ achieves a number of goals:

* Serve as an interoperable basis that allows systems to interchange
  general documents while preserving semantics.
* Allows document formats to be mapped to it and out of it, effectively
  enabling document formats to be converted to presentation
  formats without loss of meaning.
* Establishes a central data model for supporting multiple input
  formats (and syntaxes) with multiple output formats.
* Enables changes to be applied incrementally in a defined manner.

It is deliberately not a detailed document model, unlike DocBook and TEI:
it is intended to be a base document model which other document models can map to
or specialize upon.

The Basic Document document model has drawn on several existing models,
with a view to reflecting the expressiveness of existing standards,
but also to align with the capability of established document production tools.

The markup languages and document production tools that _BasicDocument_ consciously
sought to align with include:

* hypertext formats: HTML 5 and HTML 4
* document formats: OOXML, RTF, DocBook
* text markup syntaxes: Markdown and AsciiDoc


//The modelling of blocks and inline elements in particular are closely aligned with HTML.

== Scope

This document provides a lightweight document metamodel called
_BasicDocument_ for generic documents.
It is intended as an interoperable basis that allows systems to interchange
generic documents while preserving semantics.


The modelling of bibliographies and bibliographic citations is part of the reference model,
but is the subject of a separate document, <<relaton>>,
therefore they are not described in detail in this document.

The following aspects are excluded from scope:

* The specialization and profiling of this model to specialized classes of documents;

* Implementation of the reference model and serialization formats;

* The mapping of the reference model to output formats; and

* Markup schemes and syntaxes that enable creation of documents that fit the reference model.

////
The modelling of changes to documents is in scope of the _BasicDocument_ model described here, but is not described in this document.
////


[bibliography]
== Normative references

* [[[relaton,ISO 6900:--]]] footnote:[In draft], _Information and documentation -- Bibliographic reference model and serialization_
* [[[rfc3986,IETF RFC 3986]]], _Uniform Resource Identifier (URI): Generic Syntax_
* [[[iso639,ISO 639 (all parts)]]], _Codes for the representation of names of languages_
* [[[iso8601-1,ISO 8601-1]]], _AUTOFILL_
* [[[iso8601-2,ISO 8601-2]]], _AUTOFILL_
* [[[iso10118,ISO/IEC 10118 (all parts)]]], _Information technology -- Security techniques -- Hash-functions_
* [[[iso14888,ISO/IEC 14888 (all parts)]]], _Information technology -- Security techniques -- Digital signatures with appendix_
* [[[iso15924,ISO 15924]]], _Information and documentation -- Codes for the representation of names of scripts_


== Terms and definitions

[[term_class]]
=== class

structure containing a description of an entity in terms of its components

=== subclass

_class_ (<<term_class>>) which inherits from another class its component descriptions, and optionally adds to them its own component descriptions


[[term_documentmodel]]
=== document model

[alt]#model#

formal specification of the structure of a document in terms of its components and their arrangement, expressed through _classes_ (<<term_class>>)

[[term_paragraph]]
=== paragraph

subdivision of running text, normally run on throughout, that is separated from text before and after by a change of line and stands below any chapters or sections (<<term_section>>)

[.source]
<<iso5127,clause 3.5.8.07>>

[[term_block]]
=== block

_paragraph_ (<<term_paragraph>>)-level grouping of text

=== inline element

grouping of text that can be contained within a _paragraph_ (<<term_paragraph>>), including plain strings

[[term_section]]
=== section

hierarchical subdivision of a document, consisting of one or more _blocks_ (<<term_block>>), and/or one or more sections

=== identifier

character, or group of characters, used to identify or name an item of data and possibly to indicate certain properties of that item

[.source]
<<IEV,714-21-07>>


== Modelling

=== Intent

The _BasicDocument_ model expresses the structure of generic documents in a lightweight form.

It is deliberately not a detailed document model, unlike DocBook and TEI: it is intended to be a base document model which other document models can map to or specialize upon.

// For example, the Metanorma document model takes the Basic Document model as its starting point.

== Specialization

Specialization of a model consists of:

* Adding classes to a base model.
* Changing attributes of a base model class. This is not restricted to adding attributes, as is the case in typical entity subclassing; it can also include removing attributes from a class, changing their obligation and cardinality, and changing their type, including changing enumerations. Attributes can be overruled at any level; for example, standards-specific models routinely enhance the bibliographic model at the base of the hierarchy.
* For reasons of clarity, renaming classes and attributes is avoided in specialisation.

== Structure

The classes involved in the document model are of three classes:

* Sections (<<basicsection>>)
* Blocks (paragraph-level groupings of text) (<<basicblock>>)
* Inline elements (groupings of text smaller than a paragraph, including plain strings) (<<inline>>)

In the _BasicDocument_ model, the classes are in a strict hierarchical relation:

* Documents consist of sections, which consist of blocks, which consist of inline elements.
* Sections can be nested within sections (e.g. clauses and subclauses); blocks can be nested within blocks (e.g. nested lists);
* Inline elements can also be embedded within other inline elements (e.g. bold + italics).

However, sections should not be siblings of blocks, nor blocks of inline elements.
For this reason, paragraphs cannot contain other block elements, such as lists or tables.

[.example]
a list (block) is not expected to occur next to inline text within a paragraph.

NOTE: This constraint is imposed in order to maintain structural simplicity of this model.
While it sacrifices some expressive potential, the difference is minor, particularly with regards to the rendering of paragraphs.
This is a major difference between this model and the more flexible document models in XML-based schemas, such as HTML, TEI-C, and DocBook, which do not have this limitation.

The _BasicDocument_ model is most fleshed out at the level of blocks and inline elements. Specialisation of the model is expected to take place mostly at the level of prescribing particular arrangements of sections.

// this is the case for the Metanorma use of the Basic Document model.

The Basic Document model depends on the <<iso690>> bibliography model for its expression of bibliographic references. The specific bibliography model instantiation and serialization it uses is described in <<relaton>>.



[[basicdocument]]
== BasicDocument model

The _BasicDocument_ model treats all documents as collections of _sections_ (<<basicsection>>). It also adds the following metadata as part of the document model:

// Please confirm what I've assumed here for identifier
// TODO: I'm surprised it's mandatory: that certainly is not the case for Metanorma!

`identifier`:: a globally unique identifier for the document in an agreed identifier schema. The identifier is to be used for tracking interactions with the document without depending on formal document registries; it would be exemplified by a GUID, rather than a document registry identifier such as "`ISO 639`", which belongs to `bibdata`.

`bibdata`:: a bibliographic description, capturing bibliographic metadata about the document itself, including authors, title, and date of production.

`integrityValue`:: an optional digital signature of the document (<<contributionelementmetadata>>).


.Basic Document model: Document
[plantuml]
....
include::basicdoc-models/models/BasicDocument.wsd[]
....


== Metadata and bibliographic information models

The modelling of `bibdata` follows the _BibliographicItem_ class in <<relaton>>, and readers are referred to that specification. The  _BibliographicItem_ class is intended to capture document citations, and to be applicable to any document type, without any further specialisation; that is because a document can cite documents of any type.

The `bibdata` class allows the _BibliographicItem_ class to be extended with metadata specific to a document class, which appears as document metadata rather than as citation data; this information is modelled in `BibDataExtensionType`. The only extension point modelled as generically applicable in the Basic Document model is the document type, which is populated in the generic instance with the single value "document". It is assumed that particular specialisations of the document model will substitute  their own enumerations of particular subclasses of document, which will be more granular than the intentionally generic classes of document modelled in <<relaton>>.

.Basic Document model: Bibdata
[plantuml]
....
include::basicdoc-models/models/BibData.wsd[]
....


[[basicsection]]
== Section models

The _BasicDocument_ model is generic in its application, and accordingly does not do detailed modelling of the differences between sections; that is deferred for specialisations (such as the _StandardsDocument_ model). The _BasicDocument_ model only recognises the following classes of section:

* _Basic Sections_, which are leaf nodes (do not contain any sections).

* _Hierarchical Sections_, which can contain other sections. Hierarchical Sections are modelled as a subclass of Basic Sections, so the hierarchical arrangement of sections can be arbitrarily deep.

* _Content Sections_, which in the _BasicDocument_ model are treated as equivalent to Hierarchical Sections. (The distinction is currently reserved for downstream models such as Metanorma, which differentiates structurally between prefatory sections and sections in the main body of the text; differences between the two may be introduced in the Basic Document model at a later date.)

* _References Sections_, which are leaf nodes, and contain zero or more bibliographical items (as described in <<relaton>>).

All sections are modelled as having the following attributes:

`title`:: an optional title of the section.
`id`:: an optional identifier for the section, to be used for cross-references within the document. (Citations of references are modelled as cross-references to the corresponding bibliographical item in the References section.)
`blocks`:: zero or more text blocks, containing the textual content of the section (but excluding subsections, which are only present in Hierarchical Sections).
`notes`:: any notes whose scope is the entire section, rather than a specific block. Notes are modelled as a sequence of zero or more paragraphs.


NOTE: In the _BasicDocument_ model, a section can contain both blocks of text and subsections; in rendering, the blocks of text are presumed to come before the subsections. In some classes of document
//(notably for Metanorma the ISO document model)
the co-occurrence of text and subsections in a clause (or in a section) is proscribed as "`hanging paragraphs`": in order for text to be clearly identifiable by section number, those models prevent text and subsections from being siblings. That proscription is modelled as an override of this model specific to Standards documents.

.Basic Document model: Section
[plantuml]
....
include::basicdoc-models/models/Sections.wsd[]
....

[[basicblock]]
== Block models

=== General

Blocks of text are all modelled as subclasses of the _Basic Block_ class, which has the following attributes common to all blocks:

`id`:: an optional identifier for the block, to be used for cross-references.
`notes`:: any notes whose scope is the block. Notes are modelled as a sequence of zero or more paragraphs.
`contributionelementmetadata`:: attribution of the block to a specific contributor (<<contributionelementmetadata>>), to be used in change management of documents.

The _BasicDocument_ model recognises the following classes of block:

* Paragraphs (<<basicpara>>)
* Multi-paragraph blocks: Blockquotes, Reviewer comments, Admonitions (<<basicmultipara>>)
* Tables (<<basictable>>)
* Lists (<<basiclist>>): Unordered lists, Ordered lists, Definition lists
* Ancillary blocks: Figures (<<basicfigure>>),
Sourcecode (<<basicsourcecode>>),
Formulas (<<basicformula>>),
Examples (<<basicexample>>),
Preformatted blocks (<<basicliteral>>)

.Basic Document model: Block
[plantuml]
....
include::basicdoc-models/models/Blocks.wsd[]
....


[[basicpara]]
=== Paragraph

Paragraphs can contain any sequence of inline elements (<<inline>>), and optionally a text alignment (`alignment`).
Unlike the case for other document models, paragraphs _cannot_
contain other blocks, such as lists, tables, or figures: they are modelled as a basic building block of text.

NOTE: Text alignment is the only concession the modelling of paragraphs makes to rendering, and is there because the application of alignment to paragraphs, while rare, can be unpredictable from paragraph semantics. Other rendering attributes of paragraphs, such as spacing before and after, are considered to be semantically predictable and are relegated to document stylesheets.

Paragraphs have the following subclass:

* _Paragraph With Footnote_, which can also contain footnotes (<<footnote>>). While most paragraphs in a document can contain footnotes, the distinction is necessary, as footnotes are not appropriate for all instances of paragraph content in a document (e.g. sourcecode annotations) (<<basicsourcecode>>).

.Basic Document model: Paragraph
[plantuml]
....
include::basicdoc-models/models/Paragraphs.wsd[]
....

[[basicmultipara]]
=== Multi-paragraph blocks


The following classes of block are modelled as containing zero or more paragraphs:

* _Blockquote_, which also contains an optional bibliographic citation for the quotation (`source`), and an optional `author` of the quotation. The `author` attribute of the blockquote is redundant with the citation, since it restates information about the author that should be recoverable from the citation itself. It is included for convenience, in case processing the citation to extract the author is prohibitive for rendering tools.

//, and it is motivated by the separate inclusion of `author` as an attribute in blockquotes in Asciidoctor.

* _Admonition_, which captures sidebars to the main text conveying particular warnings to the reader. The Admonition block includes a name (title) and a type of admonition; the defined types for the _BasicDocument_ model are _Warning, Note, Tip, Important, and Caution_. (In rendering, distinct admonition types are often associated with distinct icons or rendering.)

* [[review]]_Review_, which is intended to capture reviewer comments about some text in the document. The Review block includes the following attributes: an optional string identifying the `reviewer` who offered the comment; an optional `date` when the comment was made; a mandatory identifier for the start of the text to which the comment applies (`appliesFrom`), and an optional identifier for the end of the text to which the comment applies (`appliesTo`).

NOTE: If the `appliesTo` identifier of a Review block is absent, the comment applies only to the span of text identified by the `appliesFrom` identifier; if it is present, the comments applies to the span of text between the start of the span of text identified by `appliesFrom`, and the end of the span of text identified by `appliesTo`.

NOTE: Admonition notes are modelled to be distinct from notes under sections or blocks.

.Basic Document model: Multi-paragraph Block
[plantuml]
....
include::basicdoc-models/models/MultiParagraphs.wsd[]
....

[[basictable]]
=== Table


Tables are modelled following the same principles as HTML tables. They contain the following elements:

`name`:: An optional label for the table.
`head`:: Zero or more table rows constituting the table header.
`body`:: One or more table rows constituting the table body.
`foot`:: Zero or more table rows constituting the table footer.
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the table. (This reflects practice in standards documents such as <<isoiecdir2>>.)
`alt`:: Alternate text to be provided for accessibility purposes, in case the table cannot be rendered accessibly.
`unnumbered`:: An optional boolean attribute indicating that the table should be excluded from any automatic numbering of tables in the document.

_Table rows_ are defined as a sequence of zero or more header cells and data cells (corresponding to HTML `th` and `td`), both classes being instances of table cells.

_Table cells_ contain either zero or more paragraphs with footnotes (<<basicpara>>), or zero or more text elements (<<textelements>>). In addition, they have the following optional rendering attributes, which are aligned with HTML:

`colspan`:: Number of columns in the underlying table grid which the cell spans.
`rowspan`:: Number of rows in the underlying table grid which the cell spans.
`align`:: Textual alignment of the cell.

.Basic Document model: Table
[plantuml]
....
include::basicdoc-models/models/Tables.wsd[]
....

[[basiclist]]
=== List

Lists are modelled following the same principles as HTML lists. All lists contain zero or more _list items_, which by default consist of an identifier (`id`), and one or more paragraphs with footnotes (<<basicpara>>). This allows individual list items in a list to be cross-referenced within the document.

Three subclasses of List are modelled.

* _Unordered lists_ are equivalent to the List base class.

* _Ordered lists_ are Lists with a `type` attribute, describing the kind of numeration applied to the List; the values allowed under the _BasicDocument_ model are _roman, alphabet, arabic, roman_upper, alphabet_upper_, corresponding to lowercase Roman numerals, lowercase alphabetic letters, Arabic numerals, uppercase Roman numerals, and uppercase alphabetic letters.

* _Definition lists_ override the definition of the List Item to be a pair of `item` (zero or more text elements: <<textelements>>) and `definition` (zero or more paragraphs with footnotes: <<basicpara>>).

.Basic Document model: List
[plantuml]
....
include::basicdoc-models/models/Lists.wsd[]
....


[[supporting-blocks]]
=== Ancillary blocks

==== General

Functionally, figures, sourcecode, formulas, preformatted blocks and examples all play a similar role, as providing illustrative content that is ancillary to the main content. However each class has its own particular structure.

.Basic Document model: Figure, Sourcecode, Formula, Example
[plantuml]
....
include::basicdoc-models/models/AncillaryBlocks.wsd[]
....


[[basicfigure]]
==== Figure

Figures are wrappers for images, and may themselves contain figures (_Subfigure_ class). They contain the following elements, all of which are optional:

`name`:: A label for the figure.
`image`:: An image (<<image>>).
`source`:: A URI or other reference intended to link to an externally hosted image (or equivalent).
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the figure. (This reflects practice in <<isoiecdir2>>.)
`footnotes`:: Optional footnotes specific to the figure. (This reflects practice in <<isoiecdir2>>.)
`figure`:: Zero or more embedded figures. (This reflects practice in e.g. <<isoiecdir2>>, and subfigures are intended to be mutually exclusive with `image`, `source`: the latter are intended for leaf node figures.)
`unnumbered`:: An optional boolean attribute indicating that the figure should be excluded from any automatic numbering of figures in the document.


[[basicsourcecode]]
==== Sourcecode

Sourcecode blocks are wrappers for computer code or comparable text. They contain the following elements:

`name`:: A label for the source code.
`filename`:: A file name associated with the source code (and which could be used to extract the source code fragment to from the document, or to populate the source code fragment with from the external file, in automated processing of the document).
`lang`:: The computer language or other notational convention that the source code is expressed in.
`content`:: The computer code or other such text presented in the block, as a single unformatted string. (The string should be treated as preformatted text, with whitespace treated as significant.)
`callouts`:: Zero or more cross-references (<<crossreferences>>); these are intended to be embedded within the `content` string, and link to annotations.
`calloutAnnotations`:: These are annotations to the source code; each annotation consists of zero or more paragraphs, and is intended to be referenced by a callout within the source code.
`unnumbered`:: An optional boolean attribute indicating that the sourcecode block should be excluded from any automatic numbering of sourcecode blocks in the document.

[[basicformula]]
==== Formula

Formula blocks are wrappers for mathematical or other formulas. They contain the following elements:

`stem`:: A STEM element (<<textelements>>), constituting the content of the formula
`definitions`:: An optional definitions list (<<basiclist>>) defining any symbols used in the formula. (This reflects practice in <<isoiecdir2>>.)
`unnumbered`:: An optional boolean attribute indicating that the formula should be excluded from any automatic numbering of formulas in the document.

[[basicliteral]]
==== Preformatted Blocks

Preformatted blocks are wrappers for text to be rendered with fixed-width typeface, and preserving spaces including line breaks. They are intended for a restricted number of functions, most typically ASCII Art (which is still in prominent use in some standards documents), and computer output. In most cases, Sourcecode blocks (<<basicsourcecode>>) is more appropriate in markup, as it is more clearly motivated semantically.

It contains the following elements (which are a subset of the elements of Sourcecode blocks):

`name`:: A label for the preformatted text.
`content`:: The preformatted text presented in the block, as a single unformatted string. (Whitespace is treated as significant.)

[[basicexample]]
==== Example

Example blocks are wrappers for open-ended example text. They consist of a combination of any of the following blocks:

* Formula
* List
* Blockquote (which is how generic text is included in an example)
* Sourcecode
* Paragraph

It also contains the following elements:

`unnumbered`:: An optional boolean attribute indicating that the example should be excluded from any automatic numbering of examples in the document.



[[inline]]
== Inline element models

=== General

Inline elements represent the components of text blocks. They are modelled in the _BasicDocument_ model as _Basic Elements_.

All Basic Elements have the following attribute:

`contributionelementmetadata`:: attribution of the element to a specific contributor (<<contributionelementmetadata>>), to be used in change management of documents.

Three subclasses of Basic Elements are modelled:

* Text elements, which contain text and associated formatting information, but which do not contain any associated identifiers. (<<textelements>>)
* ID elements, which contain identifiers. (<<image>>)
* Reference elements, which contain references to identifiers. (<<crossreferences>>)

Footnotes (<<footnote>>) are a special case of Reference element, which are not included under Basic Elements because of the need to exclude them from certain classes of paragraph (<<basicpara>>).

[[textelements]]
=== Text Elements

The modelling of text elements is substantially derived from HTML, and encompasses semantically significant formatting of text. For example, it encompasses italics and boldface (under their semantic guise of `emphasis` and `strong`); but it omits different sizes of font, as information that is typically semantically predictable, and relegated to stylesheets.

All text elements contain a localised string (<<datavalues>>).

The following elements indicate formatting, and have no further attributes:

* Monospace (corresponding to HTML `tt`, `code`)
* Keyword
* Emphasis (corresponding to HTML `em`, `i`)
* Strong (corresponding to HTML `strong`, `b`)
* Superscript (corresponding to HTML `sup`)
* Subscript (corresponding to HTML `sub`)
* Strike (corresponding to HTML 4 `s`)
* Small Caps

Text Elements also include the STEM element, representing mathematical and other formulas. This consists of a `type`, indicating which language is used to express the formula, and the content of the formula itself. By default the _BasicDocument_ model allows AsciiMath and MathML in STEM elements.


.Basic Document model: Text Elements
[plantuml]
....
include::basicdoc-models/models/TextElements.wsd[]
....

=== Empty Elements

The following elements are subclasses of Basic Element that contain no text, and are intended to represent semantically significant formatting elements:

* Line Break (corresponding to HTML `br`)
* Page Break
* Horizontal Rule (corresponding to HTML `hr`)

.Basic Document model: Empty Elements
[plantuml]
....
include::basicdoc-models/models/EmptyElements.wsd[]
....


[[image]]
=== ID Elements

ID Elements are inline elements that have an identifier (`id`), which permits them to be cross-referenced by Reference Elements (<<crossreferences>>). ID Elements in the _BasicDocument_ model do not contain text.

There are two subclasses of ID Elements in the _BasicDocument_ model:

* _Bookmarks_ are intended as anchors for cross-references which do not have scope over blocks or sections. Anchors within a block under the _BasicDocument_ model cannot span across a number of inline elements; bookmarks are intended as point anchors. For that reason, the Review block (<<review>>) has a starting reference and an optional ending reference, which can be bookmarks as well as block or section references.

* _Images_ are containers for pictorial content. They have the following attribues:

`source`:: indicating the URI of the image file

`filename`:: indicating a file name corresponding to the image, to which the image can be extracted if it is represented inline (e.g. in Base64 encoding in the URI)

`type`:: indicating the type of the image file; the Basic Document model constraints this to be one of `SVG`, `JPEG`, `GIF`, `PNG`, `PDF`.
// TODO: This ought to be relaxed

`alt`:: alternate text, supplied for accessibility
`height`:: optional attribute, which can be an integer or "auto"
`width`:: optional attribute, which can be an integer or "auto"

NOTE: The _BasicDocument_ model does not encompass audio and video files, but any extensions to the model would treat them likewise as ID Elements.

.Basic Document model: ID Elements
[plantuml]
....
include::basicdoc-models/models/IdElements.wsd[]
....


[[crossreferences]]
=== Reference Elements

Reference Elements are inline elements which reference other elements in the document, or other documents. All Reference Elements are modelled as containing the following attributes:

`text`:: The optional, unformatted textual content of the reference element.
`type`:: The type of Reference Element, prescribing how it is to be rendered. The _BasicDocument_ model recognises four types: _inline_ (referencing another element in the same document), _external_ (referencing an external document), _footnote_ (an inline reference to be rendered as a footnote), and _callout_ (an inline reference to be rendered as a callout: <<basicsourcecode>>).

The following subclasses of Reference Elements are modelled.

* Reference to Link Element: An external reference, whose `target` is defined as a URI. An optional `alt` attribute is also permitted, summarising the link content for accessibility.
* Reference to Citation Element: An external reference to a bibliographic entity, as modelled in <<relaton>> as a _citation_. In addition to the attributes of _citation_, the reference has an optional `normative` attribute (which may be used by those standards which differentiate normative and informative references), and optional `citeAs` attributes prescribing how the bibliographic citation should be rendered in the text.
* Reference to ID Element: An internal reference, whose `target` corresponds to the identifier of a section, block or ID Element within the current document.

The Reference to ID Element class in turn has the following subclasses modelled:

* Callout, for which the `type` is set to _callout_, and the `text` is constrained to be a single mandatory string. The target of the callout is understood to be the location of the callout within the source code; the extent of the target is not expressed overtly.
* Reference To ID With Paragraph Element, which associates both `text` and `content` to the cross-reference; the `content` is a sequence of one or more paragraphs (<<basicpara>>).

[[footnote]]
=== Footnote

Footnotes are modelled as a subclass of Reference To ID With Paragraph Element, which constrain their `type` to be _footnote_. The `text` attribute is the footnote reference, and the `content` attribute is the footnote contents.  The target of the footnote is understood to be the location of the footnote within the text; the extent of the target is not expressed overtly.

NOTE: Endnotes are not modelled separately from footnotes in the _BasicDocument_ model, and the use of footnotes and endnotes as realisations of annotations are normally stylistic alternatives, which would be relegated to a stylesheet.

[[datavalues]]
== Data type models

=== Basic Data Types

The following basic types are used in the definition of the _BasicDocument_ model.

* String
* URI, as defined in <<rfc3986>>.
* Language names, as defined in <<iso639>>.
* Dates and times, as defined in <<iso8601-1>>.
* Hash algorithms, as defined in <<iso10118>>.
* Digital signature algorithms, as defined in <<iso14888>>.
* Script names, as defined in <<iso15924>>.
* Localised Strings, specifying a String with optional Language and Script attributes.
* Formatted Strings, specifying a Localised String with a `format` attribute, in order to admit markup into Strings (whether XML-based or not).

.Basic Document model: Data Types
[plantuml]
....
include::basicdoc-models/models/DataTypes.wsd[]
....


[[contributionelementmetadata]]
=== Contribution Element Metadata

In addition to the Basic Data Values, the _BasicDocument_ model defines a container encoding the contribution made by a party towards a particular element in the document, with the following attributes:

`dateTime`:: The date and time when the contribution was made.
`contributor`:: The party who made the contribution, as described through the `contributor` element in <<relaton>>.
`inegrityValue`:: A digital signature of the contribution, consisting of a `hash` value and a `signature`, with an associated `publicKey`.

.Basic Document model: Contribution Element Metadata
[plantuml]
....
include::basicdoc-models/models/ContribMetadata.wsd[]
....



== Change models

=== General

The change models are provided in _BasicDocument_ to enable changes to be
applied incrementally towards a _BasicDocument_ in a defined manner.


.Basic Document model: Changes
[plantuml]
....
include::basicdoc-models/models/Changes.wsd[]
....


=== Change

The _Change_ model defines an action to be performed on an element within _BasicDocument_.

It contains the following attributes:

`target`::  The element that this action should be applied to.
`identifier`::  A unique identifier of this change.
`parentIdentifier`::  One or more unique identifiers of _Change_ objects, that this change is supposed to follow after.
`contribMetadata`::  Metadata of the contributor, see <<contributionelementmetadata>>.


=== Change set

The _ChangeSet_ model defines a collection of _Change_ data, and specifies
a unique identifier that identifies the _BasicDocument_ where this
_ChangeSet_ should be applied to.

`changes`:: The set of _Change_ data.
`documentIdentifier`:: The unique identifier that identifies the _BasicDocument_
where this _ChangeSet_ should be applied to.


=== Unique identifier

The unique identifier is used to uniquely identify a _BasicDocument_.

It contains the attribute:

`value`:: A string that uniquely identifies a _BasicDocument_.


=== Content change

==== General

The _ContentChange_ model defines possible actions
that involve modification of content within a _BasicDocument_
data element.

==== Content change action

The _ContentChangeAction_ model is used to indicate the actual content
changes that applies to the specified portion of textual content.
This is used both by the _ContentModify_ and _AttributeModify_ models
as their content are treated as pure text.

It provides the following attributes:

`action`:: A _ContentAction_ value, where it could be either `insert` or `delete`,
  indicating text to be inserted or deleted from the content.

`from`:: An `Integer` that specifies the beginning cursor position of a textual change.
`to`:: An `Integer` that specifies the ending cursor position of a textual change.
`text`:: In the case of an `insert`, a `String` to be inserted or replace the substring referred to by `from` to `to`.
`length`:: In the case of a `delete`, an `Integer` to indicate how many characters to be removed from the `from` position.
  In the case of an `insert`, an `Integer` to indicate the length of the `text` attribute.


==== Content modify

The _ContentModify_ class provides a container for a multiple _ContentChangeAction_ data.

It has the following attribute:

`actions`:: One or more `ContentChangeAction` data


=== Attribute change


The _AttributeChange_ model defines possible actions
that involve modification of an attribute within a _BasicDocument_
data element.

==== Attribute change action

Similar to _ContentChangeAction_ which it inherits from,
the _AttributeChangeAction_ class is used to specify an
actual change to an attribute.

It has the following attribute:

`attributeId`:: A `String` that identifies the attribute where the attribute change
should apply to.


==== Attribute modify

The _AttributeModify_ class provides a container for a multiple _AttributeChangeAction_ data.

It has the following attribute:

`actions`:: One or more `AttributeChangeAction` data

// TODO: This seems to only handle a string, not changing attribute name or attribute value?!


=== Node change

==== General

The _NodeChange_ model defines possible actions that involve
modification of data elements at the node level within a
_BasicDocument_.

The `target` attribute inherited from the _Change_ model indicates
the node this _NodeChange_ action applies to.


==== Node insert

The _NodeInsert_ class specifies the insertion
of a data node in a _BasicDocument_.

It has the following attribute:

`content`:: A data element conforming to _BasicElement_ to be inserted into the specified _BasicDocument_.


==== Node delete

The _NodeDelete_ class specifies the deletion of a data node in a _BasicDocument_.

It has the following attributes:

`hashValue`:: An optional string that contains the hash value of the node to be deleted for verification purposes.


==== Node move

The _NodeMove_ class specifies moving of a particular node in a _BasicDocument_
to another location within the same _BasicDocument_.

It has the following attributes:

`positionOld`:: A `ReferenceToIdElement` that indicates the position of the node's parent.
  While this seems redundant to the `target` attribute inherited from the _Change_ model,
  it is useful for verifying that the location has not changed.

`positionNew`:: A `ReferenceToIdElement` that indicates the new parent or sibling of the node.



[bibliography]
== Bibliography

* [[[isoiecdir1,ISO/IEC DIR 1]]], _Procedures for the technical work_

* [[[isoiecdir2-2004,ISO/IEC DIR 2:2004]]], _Principles and rules for the structure and drafting of ISO and IEC documents_

* [[[isoiecdir2,ISO/IEC DIR 2:2018]]], _Principles and rules for the structure and drafting of ISO and IEC documents_

* [[[iso690,ISO 690]]], _Information and documentation -- Guidelines for bibliographic references and citations to information resources_

* [[[iso5127,ISO 5127:2017]]], _Information and documentation — Foundation and vocabulary_

* [[[gbt11,CN(GB/T 1.1-2009)]]], 标准化工作导则 第1部分：标准的结构和编写 (_Directives for standardization. Part 1: The structure and drafting of standards_)

* [[[rfc7749,IETF RFC 7749]]], _The "xml2rfc" Version 2 Vocabulary_

* [[[rfc7991,IETF RFC 7991]]], _The "xml2rfc" Version 3 Vocabulary_

* [[[asciidoctor,8]]] _Asciidoctor User Manual._ https://asciidoctor.org/docs/user-manual/

* [[[ics,9]]] _ISO International Classification for Standards (ICS)_, https://www.iso.org/publication/PUB100033.html

* [[[isostage,10]]] _International harmonized stage codes_, https://www.iso.org/stage-codes.html

* [[[IEV,IEV]]], _IEV_
