[[introduction]]

:sectnums!:
== Introduction

There is a general need for interchange and interoperability of structured text amongst
information systems. While there is a plethora of richly-formatted text documents,
ranging from complex document formats like OOXML and ODF, hypertext formats like HTML,
to older formats such as RTF and presentation focused formats like PDF,
there is no standardized method of transmitting an interoperable text
structure to another system.

In addition, the popularity of lightweight text markup syntaxes like Markdown
and AsciiDoc has been hampered by practical concerns that documents generated
by such syntaxes have inherited identical issues as have the above
document formats.

This limits the exchange of structured text down to the lowest common denominator
in parsing support, which is, plain text -- that lacks any kind of
structure (human or machine understandable).

The _BasicDocument_ model is created to express the structure of generic documents
in a lightweight form.

_BasicDocument_ achieves a number of goals:

* Serve as an interoperable basis that allows systems to interchange
  general documents while preserving semantics.
* Allows document formats to be mapped to it and out of it, effectively
  enabling document formats to be converted to presentation
  formats without loss of meaning.
* Establishes a central data model for supporting multiple input
  formats (and syntaxes) with multiple output formats.
* Enables changes to be applied incrementally in a defined manner.

It is deliberately not a detailed document model, unlike DocBook and TEI:
it is intended to be a base document model which other document models can map to
or specialize upon.

The Basic Document document model has drawn on several existing models,
with a view to reflecting the expressiveness of existing standards,
but also to align with the capability of established document production tools.

The markup languages and document production tools that _BasicDocument_ consciously
sought to align with include:

* hypertext formats: HTML 5 and HTML 4
* document formats: OOXML, RTF, DocBook
* text markup syntaxes: Markdown and AsciiDoc


//The modelling of blocks and inline elements in particular are closely aligned with HTML.
